"""initial production schema

Revision ID: d4121985941e
Revises: 
Create Date: 2026-07-29 12:52:57.754248
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd4121985941e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('permissions_json', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auth_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("role IN ('admin','office','cut')", name='ck_user_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('client', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('state_json', sa.JSON(), nullable=False),
    sa.Column('versions_json', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('updated_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft','in_cut','cut_completed')", name='ck_job_status'),
    sa.CheckConstraint('version >= 1', name='ck_job_version'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_code'), 'jobs', ['code'], unique=False)
    op.create_index(op.f('ix_jobs_name'), 'jobs', ['name'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('login_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('successful', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_login_attempt_lookup', 'login_attempts', ['username', 'ip_address', 'created_at'], unique=False)
    op.create_index(op.f('ix_login_attempts_created_at'), 'login_attempts', ['created_at'], unique=False)
    op.create_index(op.f('ix_login_attempts_ip_address'), 'login_attempts', ['ip_address'], unique=False)
    op.create_index(op.f('ix_login_attempts_username'), 'login_attempts', ['username'], unique=False)
    op.create_table('cut_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_number', sa.String(length=40), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('printed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.CheckConstraint("status IN ('sent','received','printed','in_process','completed','cancelled')", name='ck_order_status'),
    sa.CheckConstraint('revision >= 1', name='ck_order_revision'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'revision', name='uq_order_job_revision')
    )
    op.create_index(op.f('ix_cut_orders_created_at'), 'cut_orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_cut_orders_is_current'), 'cut_orders', ['is_current'], unique=False)
    op.create_index(op.f('ix_cut_orders_job_id'), 'cut_orders', ['job_id'], unique=False)
    op.create_index(op.f('ix_cut_orders_order_number'), 'cut_orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_cut_orders_status'), 'cut_orders', ['status'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('size_bytes >= 0', name='ck_document_size'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_documents_job_id'), 'documents', ['job_id'], unique=False)
    op.create_table('history_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=True),
    sa.Column('field_name', sa.String(length=120), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_events_action'), 'history_events', ['action'], unique=False)
    op.create_index(op.f('ix_history_events_created_at'), 'history_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_history_events_job_id'), 'history_events', ['job_id'], unique=False)
    op.create_index(op.f('ix_history_events_request_id'), 'history_events', ['request_id'], unique=False)
    op.create_table('job_rooms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=80), nullable=False),
    sa.Column('room_code', sa.String(length=120), nullable=False),
    sa.Column('width_m', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('height_m', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('gather', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('hem_m', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('sheets', sa.SmallInteger(), nullable=False),
    sa.Column('opening', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('height_m > 0', name='ck_job_room_height_positive'),
    sa.CheckConstraint("opening IN ('central','left','right')", name='ck_job_room_opening'),
    sa.CheckConstraint('sheets BETWEEN 1 AND 10', name='ck_job_room_sheets'),
    sa.CheckConstraint('width_m > 0', name='ck_job_room_width_positive'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'source_id', name='uq_job_room_source')
    )
    op.create_index('ix_job_room_job_position', 'job_rooms', ['job_id', 'position'], unique=False)
    op.create_index(op.f('ix_job_rooms_job_id'), 'job_rooms', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_rooms_room_code'), 'job_rooms', ['room_code'], unique=False)
    op.create_table('cut_order_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('source_room_id', sa.String(length=80), nullable=True),
    sa.Column('room_code', sa.String(length=120), nullable=False),
    sa.Column('width_m', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('height_m', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('gather', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('hem_m', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('sheets', sa.SmallInteger(), nullable=False),
    sa.Column('measure_per_sheet_m', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('fabric_m', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('opening', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.CheckConstraint('height_m > 0', name='ck_order_item_height_positive'),
    sa.CheckConstraint("opening IN ('central','left','right')", name='ck_order_item_opening'),
    sa.CheckConstraint('sheets BETWEEN 1 AND 10', name='ck_order_item_sheets'),
    sa.CheckConstraint('width_m > 0', name='ck_order_item_width_positive'),
    sa.ForeignKeyConstraint(['order_id'], ['cut_orders.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cut_order_items_order_id'), 'cut_order_items', ['order_id'], unique=False)
    op.create_index('ix_order_item_order_position', 'cut_order_items', ['order_id', 'position'], unique=False)
    op.create_table('print_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('document_type', sa.String(length=40), nullable=False),
    sa.Column('is_reprint', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['cut_orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_print_logs_order_id'), 'print_logs', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_print_logs_order_id'), table_name='print_logs')
    op.drop_table('print_logs')
    op.drop_index('ix_order_item_order_position', table_name='cut_order_items')
    op.drop_index(op.f('ix_cut_order_items_order_id'), table_name='cut_order_items')
    op.drop_table('cut_order_items')
    op.drop_index(op.f('ix_job_rooms_room_code'), table_name='job_rooms')
    op.drop_index(op.f('ix_job_rooms_job_id'), table_name='job_rooms')
    op.drop_index('ix_job_room_job_position', table_name='job_rooms')
    op.drop_table('job_rooms')
    op.drop_index(op.f('ix_history_events_request_id'), table_name='history_events')
    op.drop_index(op.f('ix_history_events_job_id'), table_name='history_events')
    op.drop_index(op.f('ix_history_events_created_at'), table_name='history_events')
    op.drop_index(op.f('ix_history_events_action'), table_name='history_events')
    op.drop_table('history_events')
    op.drop_index(op.f('ix_documents_job_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_cut_orders_status'), table_name='cut_orders')
    op.drop_index(op.f('ix_cut_orders_order_number'), table_name='cut_orders')
    op.drop_index(op.f('ix_cut_orders_job_id'), table_name='cut_orders')
    op.drop_index(op.f('ix_cut_orders_is_current'), table_name='cut_orders')
    op.drop_index(op.f('ix_cut_orders_created_at'), table_name='cut_orders')
    op.drop_table('cut_orders')
    op.drop_index(op.f('ix_login_attempts_username'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_ip_address'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_created_at'), table_name='login_attempts')
    op.drop_index('ix_login_attempt_lookup', table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_name'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_code'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
